#AutoGenerated File


def export(what,where):
    import json
    d = json.load(open(f'{what}.ipynb','r'))['cells']
    with open(f'{where}.py','w') as f:
        for celda in d:
            if "#export\n" in celda['source']:
                for t in celda['source'][1:]:
                    f.write(t)
                f.write("\n")
